# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25dec93ab0b21ad2b44f171f6e561d3e71d660a874706a0c09be079f48bca28aff9041f6ac3efa7339354e5ce10406c320c5292d1f21163d7e73de715d88d4b0

test:
  secret_key_base: d76434f1d88cf052e45475133db5bdf1e418a12278bf6fbe428718a81f0abe313e87835d46f2ca54eb5a986d7a831e37039aad4f5c477c531ed8d0598713e84f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
